### PR TITLE
feat: Add monthlyQuotaConsumed field to GET /api/user API

### PR DESCRIPTION
**Pull request by jinzishuai**

### CODE REVIEW

**Comment by jinzishuai** [comment]
example output 

```json
{
    "id": "66023f85a9ddd9b0a02a529c",
    "provider": "local",
    "email": "jinzishuai@gmail.com",
    "name": "Shi Jin",
    "username": "jinzishuai",
    "avatar": null,
    "role": "ADMIN",
    "emailVerified": false,
    "plugins": [],
    "createdAt": "2024-03-26T03:22:45.669Z",
    "updatedAt": "2024-04-03T14:59:30.178Z",
    "followers": {},
    "following": {},
    "biography": "",
    "proMemberExpiredAt": "2024-10-06T04:34:07.463Z",
    "monthlyQuotaConsumed": {
        "gpt-3.5-turbo": {
            "consumed": 1,
            "quota": 30000
        },
        "gpt-4-vision-preview": {
            "consumed": 0,
            "quota": 450
        },
        "gpt-4-turbo": {
            "consumed": 0,
            "quota": 450
        },
        "gpt-3.5-turbo-16k": {
            "consumed": 0,
            "quota": 30000
        }
    }
}
```

**Review by lihyin — APPROVED** [review]
Looks great.

**Review by yinglj — APPROVED** [review]

**Comment by jinzishuai** [comment]
# Validation in Test

image

**Comment by jinzishuai** [comment]
# Compare GPT-4o vs GPT-3.5-Turbo

https://openai.com/api/pricing/

image


image

image

**Comment by jinzishuai** [comment]
## Conclusion: GPT-4o is be 10 times cost of GPT-3.5-Turbo; half of GPT-4 Turbo

So `gpt-4o`
- free: 30/month
- professional: 1,000/month

@lihyin  does this make sense?

**Pull request merged**
